### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by pnikic** [pnikic/chess#1]
- [ ]  Implement core classes (Board, Piece, Square, ...), move making, move generation and validation.

- [ ] PGN parser

- [ ] Render the board and GUI

- [ ] Write (comments and) documentation
